# Config.ps1 — sunshine.conf 및 apps.json 갱신.

# ---------------------------------------------------------------------------
# sunshine.conf 파서/직렬화 (key = value 의 플랫 구조)
# ---------------------------------------------------------------------------
function Read-SunshineConf {
    [CmdletBinding()]
    param([Parameter(Mandatory)] [string]$Path)
    $result = [ordered]@{}
    if (-not (Test-Path $Path)) { return $result }
    foreach ($line in (Get-Content -Path $Path -Encoding UTF8)) {
        $trim = $line.Trim()
        if (-not $trim -or $trim.StartsWith('#') -or $trim.StartsWith(';')) { continue }
        $eq = $trim.IndexOf('=')
        if ($eq -lt 1) { continue }
        $k = $trim.Substring(0, $eq).Trim()
        $v = $trim.Substring($eq + 1).Trim()
        $result[$k] = $v
    }
    return $result
}

function Write-SunshineConf {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] $Map
    )
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Generated by sunshine-setup. 사용자 직접 편집 가능 — 키 단위로 병합됩니다.')
    foreach ($k in $Map.Keys) {
        [void]$sb.AppendLine("$k = $($Map[$k])")
    }
    Set-Content -Path $Path -Value $sb.ToString() -Encoding UTF8 -NoNewline
}

# ---------------------------------------------------------------------------
# 가상 디스플레이의 output_name 추정
# ---------------------------------------------------------------------------
function Get-VirtualDisplayOutputName {
    <#
    .SYNOPSIS
        Sunshine 의 output_name 형식 (예: \\.\DISPLAY3) 을 반환.
        VDD 가상 디스플레이가 보이지 않으면 $null.
    #>
    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
    } catch {
        return $null
    }
    $screens = [System.Windows.Forms.Screen]::AllScreens
    if (-not $screens) { return $null }

    # FriendlyName 으로 가상 디스플레이를 찾는다 (Win32_PnPEntity 와 매칭은 어려우므로
    # 휴리스틱: Screen.DeviceName 중에 monitor name 이 'Virtual Display' 인 것을 PnP 와 교차).
    $monitors = Get-CimInstance -Namespace 'root\wmi' -ClassName WmiMonitorID -ErrorAction SilentlyContinue
    $virtualInstance = $null
    foreach ($m in $monitors) {
        $name = -join ($m.UserFriendlyName | Where-Object { $_ -ne 0 } | ForEach-Object { [char]$_ })
        if ($name -match 'Virtual') {
            $virtualInstance = $m.InstanceName
            break
        }
    }
    if (-not $virtualInstance) {
        # 최후의 수단: 가장 마지막 Screen 을 가상 디스플레이로 가정 (대부분의 경우 맞음)
        if ($screens.Count -gt 1) {
            return ($screens | Select-Object -Last 1).DeviceName
        }
        return $null
    }
    # WmiMonitorID 와 Screen.DeviceName 을 정확히 매핑하기는 어려워, 휴리스틱으로
    # 'DISPLAY' 인덱스 중 가장 마지막을 반환한다 (가상 디스플레이는 보통 마지막에 추가됨).
    return ($screens | Select-Object -Last 1).DeviceName
}

# ---------------------------------------------------------------------------
# apps.json 처리
# ---------------------------------------------------------------------------
function New-DefaultAppsJson {
    return [ordered]@{
        env  = [ordered]@{}
        apps = @(
            [ordered]@{
                name         = 'Desktop'
                'image-path' = 'desktop.png'
            }
        )
    }
}

function Read-AppsJson {
    [CmdletBinding()]
    param([Parameter(Mandatory)] [string]$Path)
    if (-not (Test-Path $Path)) { return New-DefaultAppsJson }
    try {
        $raw = Get-Content -Path $Path -Raw -Encoding UTF8
        $obj = $raw | ConvertFrom-Json -ErrorAction Stop
        return $obj
    } catch {
        Write-Log "apps.json 파싱 실패, 기본값으로 시작합니다: $($_.Exception.Message)" 'WARN'
        return New-DefaultAppsJson
    }
}

function Write-AppsJson {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] [string]$Path,
        [Parameter(Mandatory)] $Obj
    )
    $json = $Obj | ConvertTo-Json -Depth 12
    Set-Content -Path $Path -Value $json -Encoding UTF8
}

function Set-DesktopPrepCommands {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)] $AppsObj,
        [Parameter(Mandatory)] [string]$DoCmd,
        [Parameter(Mandatory)] [string]$UndoCmd
    )

    # apps 가 없거나 배열이 아니면 초기화
    if (-not $AppsObj.PSObject.Properties['apps'] -or -not $AppsObj.apps) {
        $AppsObj | Add-Member -NotePropertyName apps -NotePropertyValue @() -Force
    }
    $appsList = @($AppsObj.apps)

    # Desktop 앱 찾기
    $desktop = $appsList | Where-Object { $_.name -eq 'Desktop' } | Select-Object -First 1
    if (-not $desktop) {
        $desktop = [ordered]@{
            name         = 'Desktop'
            'image-path' = 'desktop.png'
        } | ConvertTo-Json | ConvertFrom-Json
        $appsList = @($desktop) + $appsList
    }

    # prep-cmd 갱신: 우리 do/undo 가 있으면 그대로, 없으면 추가
    $prep = @()
    if ($desktop.PSObject.Properties['prep-cmd']) {
        $prep = @($desktop.'prep-cmd')
    }
    $alreadyPresent = $prep | Where-Object {
        $_.do -eq $DoCmd -and $_.undo -eq $UndoCmd
    }
    if (-not $alreadyPresent) {
        $entry = [ordered]@{
            do       = $DoCmd
            undo     = $UndoCmd
            elevated = 'true'
        } | ConvertTo-Json | ConvertFrom-Json
        $prep = @($entry) + $prep
        $desktop | Add-Member -NotePropertyName 'prep-cmd' -NotePropertyValue $prep -Force
    }

    # apps 배열 다시 쓰기
    $newApps = @()
    $replaced = $false
    foreach ($a in $appsList) {
        if ($a.name -eq 'Desktop') {
            $newApps += $desktop
            $replaced = $true
        } else {
            $newApps += $a
        }
    }
    if (-not $replaced) { $newApps += $desktop }

    $AppsObj | Add-Member -NotePropertyName apps -NotePropertyValue $newApps -Force
    return $AppsObj
}

# ---------------------------------------------------------------------------
# 메인 진입
# ---------------------------------------------------------------------------
function Update-SunshineConfig {
    [CmdletBinding()]
    param([Parameter(Mandatory)] $Ctx)

    if (-not $Ctx.SunshineConfigDir) {
        $Ctx.SunshineConfigDir = Get-SunshineConfigDir
    }
    if (-not $Ctx.SunshineConfigDir) {
        throw "Sunshine 설정 디렉토리를 결정할 수 없습니다."
    }
    $cfgDir = $Ctx.SunshineConfigDir
    if (-not (Test-Path $cfgDir)) {
        New-Item -ItemType Directory -Path $cfgDir -Force | Out-Null
    }

    $confPath = Join-Path $cfgDir 'sunshine.conf'
    $appsPath = Join-Path $cfgDir 'apps.json'

    Write-Log "sunshine.conf 갱신: $confPath"
    if (Test-Path $confPath) { New-BackupCopy -Path $confPath | Out-Null }
    $conf = Read-SunshineConf -Path $confPath

    # 인코더
    $conf['encoder'] = $Ctx.Encoder
    if ($Ctx.Encoder -eq 'nvenc') {
        $conf['nvenc_preset']     = '1'        # P1=Fastest .. P7=Slowest. 1 권장 (저지연)
        $conf['nvenc_realtime_hags'] = 'enabled'
    }
    # 색공간: 4:4:4 (모니터/네트워크가 받쳐줄 때 텍스트 가독성 ↑)
    $conf['chroma_sampling'] = 'yuv444'
    # HDR 패스스루는 사용자가 결정 — 기본 off
    if (-not $conf.Contains('hdr')) { $conf['hdr'] = 'disabled' }

    # output_name (가상 디스플레이가 식별되면 자동 채움)
    $output = Get-VirtualDisplayOutputName
    if ($output) {
        $conf['output_name'] = $output
        Write-Log "output_name 자동 설정: $output"
    } elseif (-not $conf.Contains('output_name')) {
        Write-Log "가상 디스플레이가 아직 감지되지 않아 output_name 을 비워 둡니다. (재부팅 후 자동 매핑되거나 수동 설정 필요)" 'WARN'
    }

    # 캡처 방식 — DDX(Desktop Duplication) 가 가장 안정적
    if (-not $conf.Contains('capture')) { $conf['capture'] = 'ddx' }

    if (-not (Test-IsDryRun $Ctx)) {
        Write-SunshineConf -Path $confPath -Map $conf
    } else {
        Write-Log "[DryRun] sunshine.conf 쓰기 생략"
    }

    # apps.json 갱신
    Write-Log "apps.json 갱신: $appsPath"
    if (Test-Path $appsPath) { New-BackupCopy -Path $appsPath | Out-Null }
    $apps = Read-AppsJson -Path $appsPath

    $doScript   = Join-Path $Ctx.ToolsRoot 'do.ps1'
    $undoScript = Join-Path $Ctx.ToolsRoot 'undo.ps1'
    $doCmd   = "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$doScript`""
    $undoCmd = "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$undoScript`""

    $apps = Set-DesktopPrepCommands -AppsObj $apps -DoCmd $doCmd -UndoCmd $undoCmd

    if (-not (Test-IsDryRun $Ctx)) {
        Write-AppsJson -Path $appsPath -Obj $apps
    } else {
        Write-Log "[DryRun] apps.json 쓰기 생략"
    }

    # 변경 사항이 반영되도록 서비스 재시작
    Restart-SunshineService -Ctx $Ctx
}
